### ISSUE TITLE
Plugin should not reset view window

### ISSUE THREAD

**Issue by jeffreyameyer** [OpenHistoricalMap/ohm-date-filter#2]
Entering data into the plugin forms should not reset the view window.

Currently, any typing in the plugin "Date range" form field resets the view window to the extent of the data layer.

**Comment by Rub21** [comment]
>  resets the view window to the extent of the data layer.

@jeffreyameyer  do you mean when new date e.g `1900` is set the object are filtered ? 

![ScreenRecording2024-06-25at2 53 29PM-ezgif com-video-to-gif-converter](https://github.com/OpenHistoricalMap/ohm-date-filter/assets/1152236/4094a14a-ddb7-4c9b-b427-40a2116b0bc0)

**Comment by Rub21** [comment]
We have a new version for the plugin,
