### ISSUE TITLE
Filter window should be very tight to start... 1 day?

### ISSUE THREAD

**Issue by jeffreyameyer** [OpenHistoricalMap/ohm-date-filter#3]
It would be great if when I type in the filter date range, it goes as tight as the date range allows.

For example, if I'm editing in Iberia &. I type in something like "0909-06-19" into the "Date range" field, it should set a 1-day window and I should see something in the JOSM window that is very similar to this:

<img width="1913" alt="Monosnap OpenHistoricalMap 2024-05-24 13-32-37" src="https://github.com/OpenHistoricalMap/ohm-date-filter/assets/1494546/6f5f95fd-35cf-4f74-bf20-bd06b9ea315c">

Entering something like 0909-06 should create a 1-month window, from 0909-06-01 to 0909-06-30 (or something like that).

Entering 0909 should create a 1-year window, from 0909-01-01 to 0909-12-31.

**Comment by Rub21** [comment]
I see,  that make sense, so if the inputs are 👇 

- 0909, it should create a 1-year  window , 0909-01-01 to 0909-12-31.
- 0909-06 should create a 1-month window 0909-06-01 to 0909-06-30

What about if the User want 50 years window? is it something that could happen?

**Comment by Rub21** [comment]
done, could you try it in the new version: https://github.com/OpenHistoricalMap/ohm-date-filter/blob/main/dist/ohm-date-filter.jar
<img width="463" alt="image" src="https://github.com/OpenHistoricalMap/ohm-date-filter/assets/1152236/0b0114fd-7b97-4567-af66-ac303de6b1d6">

**Comment by Rub21** [comment]
we updated the UI , 
![image](https://github.com/user-attachments/assets/0eef6648-7279-4292-b6f5-ad5205d3e942)
