### ISSUE TITLE
Filter logic seems to be off

### ISSUE THREAD

**Issue by jeffreyameyer** [OpenHistoricalMap/ohm-date-filter#4]
Right now, when I enter a 1 day window, it doesn't yield any results.

I think it's trying to show only objects that satisfy both constraints, but it should show only objects that do NOT satisfy both constraints. That is, the < and > should be swapped.

<img width="3099" alt="Monosnap Java OpenStreetMap Editor 2024-05-24 13-43-07" src="https://github.com/OpenHistoricalMap/ohm-date-filter/assets/1494546/5fe4b987-a133-4bfe-85f8-2b9f327cd61a">

<img width="2189" alt="Monosnap Java OpenStreetMap Editor 2024-05-24 13-50-55" src="https://github.com/OpenHistoricalMap/ohm-date-filter/assets/1494546/37176c15-cca6-4aaf-89fe-0a2ce4c1993a">

**Comment by Rub21** [comment]
Good catch, i will fix that!

**Comment by Rub21** [comment]
We completed this closing this ticket
